/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Steffen' at '28.11.15 12:00' with Gradle 2.6
 *
 * @author Steffen, @date 28.11.15 12:00
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
